### ISSUE TITLE
[FEATURE] Add typescript to project

### ISSUE THREAD

**Issue by juninhokaponne** [Vijaykv5/SnapGrid#100]
**Description**

I think it would be a good implementation for the application to use Typescript given the growth of the project and community collaboration in order to avoid bugs, have better security quality and in addition to assisting in possible refactorings.

As you can see, it is used a lot because it is really good and useful.

![image](https://github.com/Vijaykv5/SnapGrid/assets/49099875/89156f38-b36c-47b2-aec2-f156bcc6252c)

**Comment by Vijaykv5** [comment]
Go for it @juninhokaponne I was going to add this issue

**Comment by juninhokaponne** [comment]
I'm working on it now, I'll open a PR in a few hours.

**Comment by juninhokaponne** [comment]
Do you think is it necessary refactor all files for .tsx and types or just add typescript and then open new issues for refactor all .files .js for .tsx ? 

I already add typescript, config and refactored index.js for index.tsx.

**Comment by Vijaykv5** [comment]
Yeah if you had typescript done , may you can refactor the other code . I think it can be solved in one issue. No need for multiple issues @juninhokaponne

**Comment by juninhokaponne** [comment]
There was a lot to change, however, it is working correctly and as expected, the video is attached to the PR as a ZIP @Vijaykv5 .
