### ISSUE TITLE
[BUG] UI is not responsive

### ISSUE THREAD

**Issue by priyanshtiwari001** [Vijaykv5/SnapGrid#109]
**Description**

When we are tried to using this application below 875px x 710px, the bar is merged inside the screen. 

**Screenshots (if applicable)**
![issue-1](https://github.com/Vijaykv5/SnapGrid/assets/64392162/bc89ff97-4aad-42bc-9e6d-0d7ff24cd3b8)
Add screenshots or other media to help explain the issue.

**Actual Behavior**

It should responsive and should not merged inside the screeen.
like this
![image](https://github.com/Vijaykv5/SnapGrid/assets/64392162/b7507975-8a56-4b8b-8235-957a74d80b03)

I love to work on this issue.

**Comment by TandinDev** [comment]
I can work on this. Can you please assign this to me.

**Comment by Vijaykv5** [comment]
@priyanshtiwari001 #90 already raised this issue.

I'll get into this issue if #90 doesn't hold good

**Comment by TandinDev** [comment]
oh, sure. Thank you.

**Comment by priyanshtiwari001** [comment]
Hi @Vijaykv5 , can you assign this issue to me . Also please add the hacktoberfest label .

**Comment by priyanshtiwari001** [comment]
Hi @Vijaykv5 , can you please assign?
