### ISSUE TITLE
Adding new Links and data's.

### ISSUE THREAD

**Issue by SaRTHaK0909k** [Vijaykv5/SnapGrid#110]
I wanted to contribute in your repo by adding more new links and descriptions of them . please assign me this issue under hacktoberfest tag

**Comment by SaRTHaK0909k** [comment]
> There's no other link than discord @SaRTHaK0909k

@Vijaykv5 What i meant to say was i added more links in links.js file in your repo.
<img width="1440" alt="Screenshot 2023-10-05 at 23 23 02" src="https://github.com/Vijaykv5/SnapGrid/assets/116540752/6506687a-7324-4569-872f-7aa47fd36412">

**Comment by Vijaykv5** [comment]
No @SaRTHaK0909k  The Current one is  good. we don't need another one :)

**Comment by SaRTHaK0909k** [comment]
@Vijaykv5 ok then can i create new issue to add social media handles buttons with their respective links ? 
if yes can you provide me the social media links that i have to add :)
