### ISSUE TITLE
No response when unknown word is searched!

### ISSUE THREAD

**Issue by ManuPrasad1208** [Vijaykv5/SnapGrid#115]
**Description**
No response when unknown word is searched!
Please describe the Feature in detail.

**Expected Behavior**
There should be a response when no result is fetched.Eg->"No Image Found" 
What should happen?

**Actual Behavior**

What happens instead?

**Screenshots (if applicable)**

![Screenshot from 2023-10-06 20-14-16](https://github.com/Vijaykv5/SnapGrid/assets/104275858/c36a0053-c329-40be-9401-32cec894bd29)

Add screenshots or other media to help explain the issue.

**Additional Information**

Add any other context or information about the issue here.

**Comment by TandinDev** [comment]
I can work on this. Can you please assign this to me,

**Comment by ManuPrasad1208** [comment]
@Vijaykv5

**Comment by Vijaykv5** [comment]
Cool go for it
