### ISSUE TITLE
Backend and UI for login / Signup page and the profile page where the login user data will show and responsiveness of the website

### ISSUE THREAD

**Issue by harshalhonde21** [Vijaykv5/SnapGrid#118]
Description :- 

🔲 Backend for Login/Signup Page:

Implement the server-side logic for user authentication.
Create APIs for user registration and login.
Ensure secure password storage and authentication.

🔲 UI for Login/Signup Page:

Design a user-friendly and visually appealing login/signup form.
Include input fields for email/username and password.
Add validation checks for input data.
Implement error handling for incorrect login/signup attempts.

🔲 Profile Page:

Develop a profile page where users can view their data.
Retrieve user-specific information from the database.
Display user details such as name, email, profile picture, etc.

🔲 User Data Display:

Dynamically populate the profile page with user data.
Ensure only authorized users can access their own profiles.
Allow users to edit and update their profile information if necessary.

**Comment by harshalhonde21** [comment]
🔴 Please assign this issue to me.

I bring 1.5+ years of expertise as a MERN Stack developer to the table. 🚀 I am committed to implementing all the features outlined in this issue. My goal is to transform the website with captivating animations and ensure it's fully responsive across all devices. 🎨💻

I'm excited to contribute to this open-source project and am ready to take on the responsibility of hosting the backend and database. This move will enhance our project's performance by seamlessly integrating backend connectivity.

I look forward to getting started and making a meaningful impact on this project. 🌟 Thank you for the opportunity to collaborate and contribute to its success. 🤝

**Comment by Vijaykv5** [comment]
I thought about it. but where we can store it?

**Comment by harshalhonde21** [comment]
we will store it in cloud.mongodb it is free cloud space provide by Mongodb AWS cloud service you can give all responsibility for safe and secure backend to me I will make this project into best dynamic project. Please assign to me make a trust to me.

**Comment by juninhokaponne** [comment]
Wouldn't it be better to create another folder within this same project just for the back-end? so people only open Pull requests or issues on the back-end or front-end ?

**Comment by harshalhonde21** [comment]
Already I am pushing /PR the backend part in another branch only.

**Comment by harshalhonde21** [comment]
@Vijaykv5  please assign i already started work on the feature/issue.

**Comment by Vijaykv5** [comment]
> Already I am pushing /PR the backend part in another branch only.

You meant new branch and new folder right just like @juninhokaponne  mentioned

**Comment by Vijaykv5** [comment]
@harshalhonde21 Are you still working on it?

**Comment by muhammedsirajudeen** [comment]
@Vijaykv5 if there is no response from his part can you assign this feature to me i think we could leverage netlify serverless functions for this feature
