### ISSUE TITLE
fix:  dark mode overlaping the snap grid side panels 

### ISSUE THREAD

**Issue by divyansshu** [Vijaykv5/SnapGrid#119]
after enabling the dark mode the Nature and Religion text is not comletely visible.
text should be seen clear just like in bright mode.

![Screenshot 2023-10-07 192358](https://github.com/Vijaykv5/SnapGrid/assets/120498621/0aa3b7fe-11f7-424d-805a-0a8a2e62f1ea)

![Screenshot 2023-10-07 191540](https://github.com/Vijaykv5/SnapGrid/assets/120498621/07cabb85-9935-488a-b7da-5786d0e19d1e)

can you assign it to me?

**Comment by vedantpotekar** [comment]
Hello, I am participating in hacktoberfest 2023, and I would love to fix this problem and contribute to this repo. 
Can you assign this issue to me? Thanks.

**Comment by Vijaykv5** [comment]
@divyansshu Are you interested in working on it?

**Comment by divyansshu** [comment]
> @divyansshu Are you interested in working on it?

yes

**Comment by Vijaykv5** [comment]
Go for it 🚀 @divyansshu
