### ISSUE TITLE
[BUG] topic list not responsive

### ISSUE THREAD

**Issue by vedantpotekar** [Vijaykv5/SnapGrid#121]
The predefined topics list is not responsive to the changing screen dimensions.

The overflowing topics should move to next line below it.

I would like to work on this and contribute as my `hacktoberfest` submission.

![image](https://github.com/Vijaykv5/SnapGrid/assets/80787731/492b700d-144d-453f-b189-1bbc74208003)

@Vijaykv5

**Comment by Vijaykv5** [comment]
Ig it's not good to do that... As it will be already enclosed in other issues
