### ISSUE TITLE
There is no home button

### ISSUE THREAD

**Issue by Shivansh175** [Vijaykv5/SnapGrid#124]
**Description**
There is no home button in your website. The logo of website can be linked to the home page. I can fix it.

**Expected Behavior**
When user clicks that logo, reaches the home page of your website.

**Comment by Vijaykv5** [comment]
Yeah I've addressed this issue in #127 Please check

**Comment by Shivansh175** [comment]
That seems good...I would love to work upon that

**Comment by Vijaykv5** [comment]
Cool I'm closing this issue for now
