### ISSUE TITLE
[FEATURE] Add Home page

### ISSUE THREAD

**Issue by Vijaykv5** [Vijaykv5/SnapGrid#127]
**Description**
This issue will focus on adding a Homepage.

**Expected Behavior**

When users clicks on website it loads the home page and on clicking on explore, they are redirected to the current page

**Actual Behavior**

There is No Home Page

**Screenshots (if applicable)**

![Snapgrid](https://github.com/Vijaykv5/SnapGrid/assets/94985341/51696373-4ac2-4ea1-9fb2-bffb12b2f9bc)

**Additional Information**

you can see the figma link here: 
https://www.figma.com/file/0geBzQsjTdg3bFVvkAK7we/Untitled?type=design&node-id=0%3A1&mode=design&t=4GvcN4lJQ3JW7UU4-1

**Comment by Shivansh175** [comment]
Hey @Vijaykv5 I would love to take upon this issue.

**Comment by Vijaykv5** [comment]
@Shivansh175 If you can do it asap, then only please take this issue

**Comment by Shivansh175** [comment]
I think I can do it by tomorrow evening

**Comment by Vijaykv5** [comment]
Cool please go for it.. also make sure for responsiveness in all devices :)

**Comment by Shivansh175** [comment]
yeah don't worry
> Cool please go for it.. also make sure for responsiveness in all devices :)

**Comment by Shivansh175** [comment]
Hey @Vijaykv5 I need a little help...are u there?

**Comment by Vijaykv5** [comment]
Yeah cool @Shivansh175 May be you can join the discord we can have more discussion there
let me know issue you're facing

**Comment by Shivansh175** [comment]
![WhatsApp Image 2023-10-08 at 19 14 26_b107e51b](https://github.com/Vijaykv5/SnapGrid/assets/112273961/6cc6f817-f226-45fe-a01c-16d8239d9b04)


I'm facing the issue in this step please guide me how can i get this unsplash API?

**Comment by Vijaykv5** [comment]
> ![WhatsApp Image 2023-10-08 at 19 14 26_b107e51b](https://user-images.githubusercontent.com/112273961/273452733-6cc6f817-f226-45fe-a01c-16d8239d9b04.jpg)
> 
> I'm facing the issue in this step please guide me how can i get this unsplash API?

https://www.educative.io/answers/how-to-get-unsplash-api-keys 
This will help you

**Comment by Shivansh175** [comment]
Thanks...
Please share your discord channel link

**Comment by Vijaykv5** [comment]
#75 

> Thanks... Please share your discord channel link

**Comment by Vijaykv5** [comment]
@Shivansh175 Would you can Make a PR today? for the issue.

**Comment by Babunshil** [comment]
@Vijaykv5  I want work on this can you please assign me

**Comment by jayprakash25** [comment]
Hey, I will start working on this issue @Vijaykv5 ...
