### ISSUE TITLE
CHANGE the Title of the Project 

### ISSUE THREAD

**Issue by Vijaykv5** [Vijaykv5/SnapGrid#13]
Hey Folks :
I'll looking to change the Name of this project.

May you can suggest some **unique ans suited** title for this project?

**Comment by veerprakash28** [comment]
Some of the suggestions: 

- ImageQuest
- PicScout
- PictoHunt
- VisualFindr

**Comment by jovyllebermudez** [comment]
Hi I'm currently looking on how to contribute here, Maybe @Vijaykv5 can suggest me what to work on.

About this issue I have cool names here. 

Pic Portal
Image Wander
Visual Voyager
Photo Pioneer
Snap Surfer
Pic Scout
Image Safari
Visual Venture
Snap Seeker
Pic Odyssey

**Comment by saku1331** [comment]
I wish to work on this issue. Kindly assign me this.

**Comment by Vijaykv5** [comment]
This issue will not be assigned @saku1331

**Comment by jovyllebermudez** [comment]
> I wish to work on this issue. Kindly assign me this.

how are you gonna solve this issue.

**Comment by Vijaykv5** [comment]
Would love to hear some unique names from all adapting to our project.

**Comment by jovyllebermudez** [comment]
Okay SnapGrid thats cool
