### ISSUE TITLE
[FEATURE] Store search query and page no in query params

### ISSUE THREAD

**Issue by VaibhavArora314** [Vijaykv5/SnapGrid#132]
**Description**

Store the search query and page no in the query params of the url.

**Expected Behavior**

If user searches something and reloads the page then his search result would not change as we will get the search query and page no from url.

**Actual Behavior**

Currently everytime user reloads, he has to search again for same thing

**Screenshots (if applicable)**

NA

**Additional Information**

What are query params?
Query parameters are a defined set of parameters attached to the end of a URL. To append query params to the end of a URL, a '? ' Is added followed immediately by a query parameter.
Ex: snapgrid.netlify.app?search=hill&page=2
Here search and page are query params

Assign me this issue, I am willing to work on it.

**Comment by Vijaykv5** [comment]
Sure @VaibhavArora314  Go for it 🚀
