### ISSUE TITLE
[FEATURE] Sticky header 

### ISSUE THREAD

**Issue by Dharmik3** [Vijaykv5/SnapGrid#139]
**Description**

If we provide the sticky header then it will be helpful for users to navigate

**Expected Behavior**

when the user scrolls down,the header will stick to the top, so if the user wants to navigate to another link then he/she does not need to scroll the page.

**Actual Behavior**

Here the header will disappear when the user is scrolling

**Comment by Vijaykv5** [comment]
We will do this once the homepage is ready

**Comment by Vijaykv5** [comment]
@Dharmik3 please work on it!

**Comment by dev-palwar** [comment]
Can i work on it?

**Comment by Dharmik3** [comment]
@Vijaykv5 I work on it

**Comment by dev-palwar** [comment]
I've made an PR. Can you review it?

**Comment by Vijaykv5** [comment]
@Dharmik3 please work on it

**Comment by Dharmik3** [comment]
I made the PR #163 please review it.

**Comment by Vijaykv5** [comment]
Please see those reviews
