### ISSUE TITLE
Feature Request: About Page

### ISSUE THREAD

**Issue by nuelladev** [Vijaykv5/SnapGrid#142]
**Description**

Feature Request: About Page

 Introduce an "About Page" to the website. The purpose of this page is to provide users with essential information about the application, its purpose, the team behind it, and any other relevant details that can enhance user understanding and trust.

**Expected Behavior**

When users navigate to the "About Page," they should encounter a well-structured and informative page that includes the following elements:

Introduction: The page should start with a warm and concise introduction that explains the purpose and mission of the application or website. This sets the tone for the rest of the content.

- History and Milestones: If applicable, highlight key milestones and achievements in the project's history. This could include major updates, or significant accomplishments.

-Acknowledgements: If necessary, recognise and thank the contributors that have played a significant role in the development of the application.

**Actual Behaviour**

Currently, the  website lacks an "About Page." Users do not have a dedicated place to find detailed information about the project, team, vision, and other important details, if need be.

**Comment by Vijaykv5** [comment]
Hi @nuelladev Thanks for suggetion. But we are moving to make the Homepage.
after that we can look into it

**Comment by Vijaykv5** [comment]
@nuelladev you can work on this now.l
But tell me what are including in that about us page?

**Comment by nuelladev** [comment]
Hello @Vijaykv5,

After reviewing the homepage, I had some reservations about the need for a separate about page. The homepage already seems to provide all the essential information.

Do you still believe it's necessary to have an about page? On a related note, I had some ideas for adding specific details on the about page and instructions on how to use the website, but I'd like to confirm if it's still required.
