### ISSUE TITLE
[BUG] Missing configuration redirect rule for your site

### ISSUE THREAD

**Issue by rhnas110** [Vijaykv5/SnapGrid#144]
**Description**
When I refresh the page https://snapgrid.netlify.app/search, the page is not found from netlify.

**Expected Behavior**
When I refresh the page https://snapgrid.netlify.app/search, it should return the page https://snapgrid.netlify.app/search

**Actual Behavior**
When refreshing the page https://snapgrid.netlify.app/search, it becomes not found page

**Screenshots (if applicable)**
https://github.com/Vijaykv5/SnapGrid/assets/51848196/8e639b65-a7b3-4743-850d-b9f03318a311

**Additional Information**
Hi Sir @Vijaykv5 
I'm new to open source contributions and I'd really want to contribute to your project! Can you please assign this issue to me? Thank you for your response Sir @Vijaykv5 . I also participated in Hacktoberfest2023.

**Comment by Varun-Kolanu** [comment]
Can you please assign me this issue? @Vijaykv5

**Comment by Vijaykv5** [comment]
@rhnas110 Are you working on this issue?

**Comment by rhnas110** [comment]
@Vijaykv5 Yes sir, I need an assignment from you to create a PR for my submitted issue

**Comment by Vijaykv5** [comment]
@Varun-Kolanu We follow first come rule 
Since @rhnas110 first asks for assignment I'm assigning it to him

**Comment by Varun-Kolanu** [comment]
> @Varun-Kolanu We follow first come rule Since @rhnas110 first asks for assignment I'm assigning it to him

Ok np sir
