### ISSUE TITLE
[FEATURE] Infinite scroll and enhanced image lazy loading

### ISSUE THREAD

**Issue by SuyashRajput** [Vijaykv5/SnapGrid#145]
Simple infinite scroll where API will be fetched when we reach at the bottom
AND
Enhanced image lazy loading with intersection observer

**Comment by Varun-Kolanu** [comment]
Please assign this issue to me @Vijaykv5 
I have worked earlier on infinite scrolling

**Comment by SuyashRajput** [comment]
I have issued the task for myself I talked to him on discord
