### ISSUE TITLE
[BUG] There's no way for user to redirect to Home Page

### ISSUE THREAD

**Issue by Varun-Kolanu** [Vijaykv5/SnapGrid#147]
**Description**

When you go to /search, you cannot go to Home Page until you edit the url

**Expected Behavior**

There should be a way for user to go to Home Page without editing the Url

**Actual Behavior**

No button is assigned for redirection to Home Page

Please assign this issue to me @Vijaykv5

**Comment by veerendra19codes** [comment]
can i work on this?

**Comment by veerendra19codes** [comment]
is this issue closed?

**Comment by Vijaykv5** [comment]
@veerendra19codes Issue is already under work by @Varun-Kolanu
