### ISSUE TITLE
[BUG] Anomaly in button functionality 

### ISSUE THREAD

**Issue by unm07** [Vijaykv5/SnapGrid#149]
**Description**

The entire div of the explore button acts like a button instead of just the button

**Expected Behavior**

Just the button should act like a button, not the div

**Screenshots**
![Screenshot 2023-10-14 141947](https://github.com/Vijaykv5/SnapGrid/assets/110920768/1d60864c-62be-4266-a0ee-74b1ea630fd4)

**Comment by unm07** [comment]
can I work on this?

**Comment by Vijaykv5** [comment]
Please describe your issue. I didn't get it at all

**Comment by unm07** [comment]
Apologies if my earlier message was unclear. The issue is that clicking anywhere inside the <div> element (highlighted in blue), not just the button itself, is triggering the button's functionality.

I have attached a video for further clarification:

https://github.com/Vijaykv5/SnapGrid/assets/110920768/09734588-858a-440c-8770-7d78791c40c1

**Comment by Vijaykv5** [comment]
I don't think we need to encounter this issue? As it's understood as we user clicks on explore button, it redirects to the search page

**Comment by Vijaykv5** [comment]
@unm07 what you think mate??

**Comment by unm07** [comment]
If you don't want to change it, then it's okay. I was just trying to fix it and get a PR. No worries.😄
