### ISSUE TITLE
[BUG] Banner doesn't change if Searched for query that is in Selection Menu

### ISSUE THREAD

**Issue by Varun-Kolanu** [Vijaykv5/SnapGrid#153]
**Description**

Banner remains same if Searched for query in Selection Menu

**Expected Behavior**

When searched for any item search that is in Selection Menu, the banner and description should change and button in Selection Menu should become active

**Actual Behavior**

Banner and description remains the same and button is not becoming active

**Screenshots (if applicable)**

![image](https://github.com/Vijaykv5/SnapGrid/assets/112728411/0ec01132-f4b8-444b-a2aa-8b631beb0eea)

If I search for Camera now, which is in the selection menu, Photos from unsplash are shown but the banner photo and description that was earlier in Nature didn't get changed. And also, button "Camera" in the selection menu didn't get active/highlighted

![image](https://github.com/Vijaykv5/SnapGrid/assets/112728411/56d5a549-fb3f-435d-a5b6-12f3af9b6691)

Please assign this issue to me @Vijaykv5 
I am making a PR please review

**Comment by Vijaykv5** [comment]
Cool
