### ISSUE TITLE
The search should happen as soon as I start typing

### ISSUE THREAD

**Issue by abhijeetgurle** [Vijaykv5/SnapGrid#155]
**Description**

There shouldn't be any need to press enter after typing something in the search input.

**Expected Behavior**

The search should happen as soon as I start typing. Can use debounce to reduce api calls.

**Actual Behavior**

Need to press enter whenever I finished typing something in search bar

**Comment by Vijaykv5** [comment]
Yes this is an interesting issue.
@abhijeetgurle do you like to work on this issue?
