### ISSUE TITLE
[FEATURE] Build sign up page

### ISSUE THREAD

**Issue by Mayank-Sharma17** [Vijaykv5/SnapGrid#162]
**Description**

When a user clicks the sign-up button, a sign-up page must occur, maybe authentication will be added in the future. Please assign me to work on this.

**Comment by Vijaykv5** [comment]
Are you working on it @Mayank-Sharma17

**Comment by Mayank-Sharma17** [comment]
@Vijaykv5 you can merge @aasimtaif PR as I am unable to complete it due to some other work.

**Comment by muhammedsirajudeen** [comment]
can i work on this?

**Comment by aasimtaif** [comment]
Hi @Vijaykv5   are you going to merge the PR ??
