### ISSUE TITLE
[FEATURE] most recent three search

### ISSUE THREAD

**Issue by lcrojano** [Vijaykv5/SnapGrid#164]
**Description**

Implement the ability to store and display the user's most recent three search terms in local storage.

**Expected Behavior**

The application should visually display the last three search terms entered by the user.

**Actual Behavior**

Currently, when the user exits the application, their most recent search terms are lost.

**Screenshots (if applicable)**

![image](https://github.com/Vijaykv5/SnapGrid/assets/5177737/5286ef53-b245-4ced-9845-d4132378d57b)

Additional Information

I am committed to implementing this feature to improve the user experience.

**Comment by Vijaykv5** [comment]
@lcrojano I don't think we don't need this feature as Right now Our Search page has most of the elements..
We are making it more precise

So for That I'm not taking into account this feature now
