### ISSUE TITLE
Add An attractive footer 

### ISSUE THREAD

**Issue by Bisalkumar1** [Vijaykv5/SnapGrid#166]
please assign this issue to me under Hacktoberfest 2023

**Comment by Vijaykv5** [comment]
@Bisalkumar1 Yes we can add it... But Only in main page..We don't want them in the Search page

I'm planning to make something like this. **Do checkout for reference** 
<img width="1315" alt="Screenshot 2023-10-23 at 11 59 14 AM" src="https://github.com/Vijaykv5/SnapGrid/assets/94985341/9c74f949-e054-4066-8890-55a6924add02">

**Comment by Bisalkumar1** [comment]
ok

**Comment by Sanketmane2323** [comment]
Hey i would like to work on this issue

**Comment by Vijaykv5** [comment]
> Hey i would like to work on this issue

I appreciate your efforts in contributing to this repo.  But it already assigned to @Bisalkumar1 ..Please look into the unassigned issue.

**Comment by SumanKisku** [comment]
@Bisalkumar1 hi are you still working on this?
