### ISSUE TITLE
[BUG] Photographer name is not shown on pictures

### ISSUE THREAD

**Issue by sebiboga** [Vijaykv5/SnapGrid#168]
**Description**

Show the photographer name / and link to his own profile

**Comment by SumanKisku** [comment]
Can I take on this issue?

**Comment by Vijaykv5** [comment]
Is that necessary? Also How you think we can get the photographer's details

**Comment by sebiboga** [comment]
maybe through the API

**Comment by muhammedsirajudeen** [comment]
actually when we get back the results there is a user property on the result object which i guess is the username of the person uploaded that picture i guess we can work on that 
![image](https://github.com/Vijaykv5/SnapGrid/assets/43089951/8e9c8da9-f6c5-46cf-922d-1b42468e43b7)

**Comment by Vijaykv5** [comment]
Does anyone willing to work on it
@sebiboga @muhammedsirajudeen

**Comment by muhammedsirajudeen** [comment]
@Vijaykv5 iam willing to work on it

**Comment by Vijaykv5** [comment]
Sure go ahead 

> @Vijaykv5 iam willing to work on it

**Comment by Vijaykv5** [comment]
Haha sure :)

> I'm just a tester; Let me know when I can test ;)

**Comment by Debshibraj123** [comment]
@Vijaykv5  please assign me this issue I can solve this
