### ISSUE TITLE
[FEATURE] Hey Vijay We Can Add Feature of Add to Favourite Image.

### ISSUE THREAD

**Issue by JavidSumra** [Vijaykv5/SnapGrid#169]
Vijay, we can currently implement this feature using 'LocalStorage' and enhance it later on.
Please Assign this feature to me under hacktoberfest.

**Comment by Vijaykv5** [comment]
Yes but how how we display it in frontend...ls it like adding a section in Navbar for liked Images

**Comment by JavidSumra** [comment]
Vijay, I've already implemented this feature, and I'd like to share some of its key features. Please take a look and let me know your thoughts.
![Screenshot 2023-10-23 131615](https://github.com/Vijaykv5/SnapGrid/assets/112365664/ff786cf8-4548-44b2-ba3c-59f7cb486bf5)
![Screenshot 2023-10-23 131706](https://github.com/Vijaykv5/SnapGrid/assets/112365664/53c8fe26-b8dd-4709-add3-371e22b29d3a)

**Comment by Vijaykv5** [comment]
Yeah I got your point but where the User can see their liked images?

**Comment by JavidSumra** [comment]
Hey Vijay I will create a new route or label by tomorrow to see Favourite Images.

**Comment by JavidSumra** [comment]
Hi Vijay, I've implemented this using a toggle button, and I've attached an image to illustrate this feature. However, please note that it works on an individual basis, not for a general application.
![Screenshot 2023-10-23 193109](https://github.com/Vijaykv5/SnapGrid/assets/112365664/327d0b26-6091-493d-85ea-be9fdc2bd48d)

**Comment by JavidSumra** [comment]
Hey @Vijaykv5 can you please reply to this feature

**Comment by Vijaykv5** [comment]
I've replied in PR. Please check

**Comment by JavidSumra** [comment]
Hello @Vijaykv5,
I've submitted a pull request, and I would appreciate it if you could take a look and provide feedback when you have the time. Thank you!

**Comment by JavidSumra** [comment]
Hey @Vijaykv5 can you please add Label hacktoberfest on this Issue please.
