### ISSUE TITLE
[FEATURE] Add Animation Effect

### ISSUE THREAD

**Issue by Vijaykv5** [Vijaykv5/SnapGrid#171]
**Description**

Everything must add like an animation in homepage

**Expected Behavior**

Text and Images should Animate

**Actual Behavior**

Nothing happens 

**Screenshots (if applicable)**

https://projectshut.vercel.app/

**Additional Information**

Do check out the link for reference.
I'm planning to have similar type of animation

**Comment by nishaaannnt** [comment]
hey @Vijaykv5 i can work on this.

**Comment by Vijaykv5** [comment]
Cool go for it @nishaaannnt 🚀

**Comment by nishaaannnt** [comment]
hey @Vijaykv5 can you please add the hacktober label too. I want to complete this under hacktoberfest. 
Thank you !

**Comment by Vijaykv5** [comment]
@nishaaannnt Done

**Comment by Vijaykv5** [comment]
do we can make like this https://projectshut.vercel.app/

As I saw  The earlier animation as usual from top-bottom

**Comment by nishaaannnt** [comment]
hey @Vijaykv5  I have made the animation from X axis. 
About the bouncy effect that may be not very good for loading of the website and may cause issues.

 

https://github.com/Vijaykv5/SnapGrid/assets/100792085/d80636e9-235f-43a5-a0c6-e9822b081ff6

Let me know if something needs to be done

**Comment by nishaaannnt** [comment]
ok will do @Vijaykv5

**Comment by nishaaannnt** [comment]
@Vijaykv5 here you go  
let me know if this looks good

https://github.com/Vijaykv5/SnapGrid/assets/100792085/b1a3eaa6-24b0-434e-92ee-2bc331787f6e

**Comment by Vijaykv5** [comment]
It looks cool.. Please animate the right side image too in same way 👍🏻

**Comment by nishaaannnt** [comment]
@Vijaykv5 


https://github.com/Vijaykv5/SnapGrid/assets/100792085/336d0b3c-0438-4f5e-ab21-875c6b0d7cea

**Comment by Vijaykv5** [comment]
Nice add a PR 👍. Will it reflect for mobile view?

**Comment by nishaaannnt** [comment]
yep it will @Vijaykv5
