### ISSUE TITLE
[FEATURE] remember the users choice for dark or light theme

### ISSUE THREAD

**Issue by muhammedsirajudeen** [Vijaykv5/SnapGrid#172]
**Description**

when a users prefers dark theme and they go onto the search page and returns back and they revisit the page they have to select the dark mode button again instead now we store the last selected theme to locatstorage and on initial render we select the user prefered theme 

**Expected Behavior**
the user clicks on the dark mode and refresh the page or revisits the page the preferred theme is lost
What should happen?
when user refreshes or comes back to the page their last selected theme should be loaded
**Actual Behavior**
when a user selects dark mode and refreshes or revisits the page it should still show their preferred selection of theme

**Screenshots (if applicable)**

Add screenshots or other media to help explain the issue.

**Additional Information**

can you please add the hacktober fest label to this . Also i have already completed the feature

**Comment by Vijaykv5** [comment]
cool @muhammedsirajudeen go for it 🚀

**Comment by muhammedsirajudeen** [comment]
i have a pr that is yet to be merged should i wait for it to merge to keep the commit history clean or can i combine this feature with that pr and create a fresh pr

**Comment by muhammedsirajudeen** [comment]
hey i have combined both and created a new pr
