### ISSUE TITLE
I Will add The Hover Button Effects To Your Site

### ISSUE THREAD

**Issue by Radhey644** [Vijaykv5/SnapGrid#173]
I've observed the absence of hover effects on buttons. I'm eager to enhance them for a more engaging user experience. I'd appreciate the opportunity to contribute.

**Comment by Radhey644** [comment]
@Vijaykv5 Sir,
pls look into my concern

**Comment by Vijaykv5** [comment]
It's not needed @Radhey644 as we are not more into looking for Designs improvement.
In future we may can add it

**Comment by Radhey644** [comment]
it would be a honor if you put me through this task now.
as i want to gain the hacktoberfest badge so i will do it for u in return of that.

**Comment by Vijaykv5** [comment]
Yeah but it would not be valuable..
I appreciate your efforts but please may look into other issues which are open
