### ISSUE TITLE
Button UI needs to be improved in order for the good user's experience

### ISSUE THREAD

**Issue by nishant3721** [Vijaykv5/SnapGrid#178]
**Description**

Button UI should look somewhat good, e.g., the hover effect

**Expected Behavior**

Should be user's friendly

**Actual Behavior**

The button is simple to is very difficult to predict the actions

**Screenshots (if applicable)**

![image](https://github.com/Vijaykv5/SnapGrid/assets/76558924/dca2fe78-cdf5-46ac-af65-980e7d0d299b)

**Additional Information**

N/A

**Comment by nishant3721** [comment]
I would like to work on this issue!

**Comment by Vijaykv5** [comment]
Please describe the Issue

**Comment by nishant3721** [comment]
@Vijaykv5 On hovering the button it is not doing any activity, maybe we should try to put some animation in the button, so that it will become attractive!
