### ISSUE TITLE
[BUG] ui bug in the homepage leaving overflowed contents background as white 

### ISSUE THREAD

**Issue by muhammedsirajudeen** [Vijaykv5/SnapGrid#180]
**Description**

I dont know if this was a design choice or a small overlooked mistake in the home page when divs height was set to h-screen it just covers the visible viewport and in small devices there is a little bit content outside the view port so its not getting the default background linear gradient style 

**Expected Behavior**
the whole screen should have been the same color instead on smaller devices there is an area outside viewport with background color as white 
What should happen?
the entire background should follow the same linear gradient
**Actual Behavior**

What happens instead?

**Screenshots (if applicable)**
currently the screen is 
![image](https://github.com/Vijaykv5/SnapGrid/assets/43089951/c3a2fa00-3cae-43dc-81ce-add80988e57b)

expected screen style 
![image](https://github.com/Vijaykv5/SnapGrid/assets/43089951/762e9c73-42f6-4b30-aa3f-78977844c41c)

Add screenshots or other media to help explain the issue.

**Additional Information**

Add any other context or information about the issue here.
i actually dont know if its a design choice. if its not can you please add the hacktoberfest label and assign this issue to me

**Comment by Vijaykv5** [comment]
no it's not @muhammedsirajudeen ...but I would like to see the desktop version too

**Comment by muhammedsirajudeen** [comment]
desktop version with the bug
![image](https://github.com/Vijaykv5/SnapGrid/assets/43089951/3c4add8c-d01c-4eeb-b7c7-c7610ba087b6)
after solving the bug
![image](https://github.com/Vijaykv5/SnapGrid/assets/43089951/cd810fb2-7d26-46f2-8f2f-8e16fc47aaab)

**Comment by Vijaykv5** [comment]
Cool go fir it!
