### ISSUE TITLE
[BUG] doc page's ui is broken(unresponsive) on mobile devices

### ISSUE THREAD

**Issue by muhammedsirajudeen** [Vijaykv5/SnapGrid#181]
**Description**

on mobile devices the docs page of the snapgrid website is broken meaning that that the ui is very malformed 

**Expected Behavior**
expecting it to be responsive and have a uniform look
What should happen?
when opening the site on smaller devices the docs page is broken absolutely
**Actual Behavior**

What happens instead?

**Screenshots (if applicable)**
desktop version (works perfectly)
![image](https://github.com/Vijaykv5/SnapGrid/assets/43089951/1b196791-4691-48be-b4d1-23197be2148e)

mobile version the ui is not responsive and also broken
![image](https://github.com/Vijaykv5/SnapGrid/assets/43089951/b0499b2b-a0c2-4e29-8ab3-417332c5a0a1)

Add screenshots or other media to help explain the issue.

**Additional Information**

Add any other context or information about the issue here.
please assign this issue to me and kindly add the hacktober fest label

**Comment by Vijaykv5** [comment]
Yes the docs page is not responsive... Please fix that issue...
