### ISSUE TITLE
[FEATURE] focus on sorted search button 

### ISSUE THREAD

**Issue by weberankit** [Vijaykv5/SnapGrid#182]
Basically When the user visits this page https://snapgrid.netlify.app/search?search=History&page=1
 i.e. snap grid page and tap on the filter button the filter button background color should change after clicking.
 
 how to do that?
I am going to use the UseState hook for this 
it will enhance the user experience
could you plz assign me under the Hacktoberfest tag
![image](https://github.com/Vijaykv5/SnapGrid/assets/94105514/c3caac4e-4ffa-4400-a11a-d679ba4b0d6c)

**Comment by weberankit** [comment]
@Vijaykv5

**Comment by Vijaykv5** [comment]
@weberankit we are not more dealing with UI. Will be focussing on major functionalities 
I think we can look at this feature later

**Comment by weberankit** [comment]
@Vijaykv5  I understand but not only these features I also want to add the preview image before downloading .
there are no such features there that allow the user to preview images before downloading it will be a great User experience

**Comment by weberankit** [comment]
okay
