### ISSUE TITLE
[DOCS] found a small typo in the docs page

### ISSUE THREAD

**Issue by muhammedsirajudeen** [Vijaykv5/SnapGrid#185]
**Description**
there is a small typo in the doc page 

Please describe the issue in detail.
where in step 5 the command is git pull origin main as our top branch is master the command should be git pull origin master or just git pull its a slight typo
**Expected Behavior**
the command should be just git pull or git pull origin master 
What should happen?

**Actual Behavior**

What happens instead?

**Screenshots (if applicable)**

Add screenshots or other media to help explain the issue.
what it is now
![Screenshot from 2023-10-25 21-59-09](https://github.com/Vijaykv5/SnapGrid/assets/43089951/77e85584-c8de-40af-bf8f-9398fa927b1d)
what it should be 
![image](https://github.com/Vijaykv5/SnapGrid/assets/43089951/8c020ea9-5da1-41d2-a07b-61f921ec80bb)

**Additional Information**

Add any other context or information about the issue here.
could you add hacktoberfest label and assign this to me.

**Comment by eyeaadil** [comment]
@muhammedsirajudeen  i  want to work on this issue please assign me

**Comment by muhammedsirajudeen** [comment]
well i do not have the repository rights to assign anyone but sure @Vijaykv5 can assign this to you

**Comment by Vijaykv5** [comment]
Yes Please go for it.
@muhammedsirajudeen Are you interested to work on it or else I can assign @eyeaadil

**Comment by muhammedsirajudeen** [comment]
you can assign @eyeaadil
