### ISSUE TITLE
[FEATURE] Hamburger menu in the navigation bar for mobile devices 

### ISSUE THREAD

**Issue by muhammedsirajudeen** [Vijaykv5/SnapGrid#187]
**Description**
Adding a hamburger menu in the navigation bar for improved user experience 
Please describe the Feature in detail.
in the desktop version of the website the navbar is well put up but when coming to the mobile devices the user is not able to browse the pages in the navigation bar so by adding a hamburger menu the mobile user would be able to browse through the page more seemlessly

**Expected Behavior**
in the navigation bar of the website the user would be able to browse to the docs page and the github page and signup page seemlessly but in the mobile version the navigation bar is empty the user would not be able to get to the doc page from the navigation bar
What should happen?
we are adding a hamburger menu which collpases to show the docs link,github link and signup page link
**Actual Behavior**

What happens instead?

**Screenshots (if applicable)**
desktop version
![image](https://github.com/Vijaykv5/SnapGrid/assets/43089951/ea62923c-36e3-4dd7-9d9e-9f2fd58ebf1b)

mobile version
![image](https://github.com/Vijaykv5/SnapGrid/assets/43089951/7760f8f9-eca2-4036-a887-97a5937635e2)

mobile version after implementing the feature
![image](https://github.com/Vijaykv5/SnapGrid/assets/43089951/0234b575-c6aa-4314-85bb-69bc62fa8eb9)

![image](https://github.com/Vijaykv5/SnapGrid/assets/43089951/89b44b1a-94cb-4ad6-9755-61a98403aa2f)

Add screenshots or other media to help explain the issue.

**Additional Information**

Add any other context or information about the issue here.
can u please add the hacktoberfest label and kindly assign this issue to me

**Comment by Vijaykv5** [comment]
That's seems a feature I would like to link with ... but @muhammedsirajudeen can you add a animation too, because I don't wanna add new issue for that.
May be from top-botton animate while clicking on hamburger button
Please suggest your ideas

**Comment by muhammedsirajudeen** [comment]
surely i would add the animation too
