### ISSUE TITLE
[FEATURE] Adding a serch icon in search bar

### ISSUE THREAD

**Issue by AnujRathour** [Vijaykv5/SnapGrid#189]
**Description**

Addition of search icon in search bar will provide better user experience

**Expected Behavior**

search icon will show in search bar

**Actual Behavior**

No search icon in search bar available right now

**Screenshots (if applicable)**

<img width="402" alt="image" src="https://github.com/Vijaykv5/SnapGrid/assets/119128989/7e4d0d90-4ee9-463f-b7c7-b61ec9fd7c1e">

**Comment by AnujRathour** [comment]
@Vijaykv5 I would like to work on this please assign it to me.

**Comment by Vijaykv5** [comment]
We earlier had an button @AnujRathour and we removed it to keep it minimal.
So I think we don't need that page as already the search page is overflowing
