### ISSUE TITLE
[Feat]: Addition of Login button and page on home page.

### ISSUE THREAD

**Issue by AnujRathour** [Vijaykv5/SnapGrid#190]
**Description**
I would like to add Login Button and page  (only UI) on home page.

**Comment by AnujRathour** [comment]
@Vijaykv5 I would be happy if I can work on this feature.Please assign it to me.

**Comment by Vijaykv5** [comment]
its already under work #162

**Comment by AnujRathour** [comment]
Ok Thanks for your response.

**Comment by AnujRathour** [comment]
Ok Thanks for your response.
