### ISSUE TITLE
[BUG] When a user initially arrives on the search page, no images are visible.

### ISSUE THREAD

**Issue by JavidSumra** [Vijaykv5/SnapGrid#198]
**Description**
When a user first visits the search page, no images are displayed. The main idea is to showcase random images when users arrive on the **Search Page**.

**Expected Behavior**
Upon landing on the search page, a random image should be prominently displayed.
**Actual Behavior**
When the User Lands on **Search Page** for the First Time There are No Images.
**Screenshots (if applicable)**
 
![Before](https://github.com/Vijaykv5/SnapGrid/assets/112365664/0f25e974-f1d0-4a53-8742-5024c4b3630b)

![After](https://github.com/Vijaykv5/SnapGrid/assets/112365664/b0a4e764-9998-4a3a-94e4-f10afbb89571)

**Additional Information**
Hey @Vijaykv5 Please consider assigning this issue to me, as I have successfully resolved the problem.

**Comment by JavidSumra** [comment]
Hey @Vijaykv5 Please Check out this PR please.

**Comment by JavidSumra** [comment]
Hey @Vijaykv5 please Reply on this PR so I can work further.

**Comment by Vijaykv5** [comment]
@JavidSumra Oh It's not mate. 

We don't need any images to be displayed when user is on search page without searching any keywords.
It's the standard way.

**Comment by Vijaykv5** [comment]
In future contribution. Please make sure to get a valid feedback from me and your assignment on the issue...

For this I'm closing this issue and PR related to it
