### ISSUE TITLE
[FEATURE] Optimizing Hover Effects for Image.

### ISSUE THREAD

**Issue by Abhishek2nayak** [Vijaykv5/SnapGrid#203]
**Description**
When a user hovers over the images, the blurring of the border can potentially detract from the overall user experience. Furthermore, the transition lacks smoothness, which may compromise the user's satisfaction with the interface

**Expected Behavior**
When a user hovers over an image, a smooth transition should be implemented, accompanied by a sutable drop shadow effect to make the image stand out. Additionally, it is important to ensure that the border remains unaffected and does not become blurred

**Actual Behavior**
When a user hovers over an image, applying a blur effect to the entire image may cause it to blend in with the surrounding images instead of standing out.

**Comment by Abhishek2nayak** [comment]
@Vijaykv5 I would like to work on this issue .  please assign it to me under hacktoberfest.

**Comment by Vijaykv5** [comment]
I think its not needed @Abhishek2nayak as per the Description you mentioned.
Please feel free to add a screenshot or more detailed (video)
