### ISSUE TITLE
[BUG] Suggested search terms are overflowing the page

### ISSUE THREAD

**Issue by SumanKisku** [Vijaykv5/SnapGrid#205]
**Description**

Suggested search terms are overflowing on x axis and breaking the page layout on mobile devices

**Expected Behavior**

The user should be able to scroll the suggested terms horizontally **ONLY** not the page with it.

**Actual Behavior**

Breaking the layout of the page.

**Screenshots (if applicable)**

![Screenshot from 2023-10-28 12-59-45](https://github.com/Vijaykv5/SnapGrid/assets/7936345/f582f089-d4e0-4fe8-aae7-ff43538fbfb7)

**How to Reproduce**
1. Visit - https://snapgrid.netlify.app/search on mobile
2. Try to scroll horizontally

**Comment by SumanKisku** [comment]
Hi @Vijaykv5 please assign me this issue

**Comment by JavidSumra** [comment]
Hey @SumanKisku i already raised the same issue and I am working on it.

**Comment by SumanKisku** [comment]
@JavidSumra oh! Sorry man I missed your issue.
