### ISSUE TITLE
[BUG] The search page is not responsive.

### ISSUE THREAD

**Issue by aniketkuma-r** [Vijaykv5/SnapGrid#206]
**Description**

The Search page in snapgrid app is little unresponsive.  The width of page is not according to device window size. This is happening because of overflow of div in which tags of photo like (Nature, Shoes, Camera, Birds, ...) have written. This can be fixed by defining the width size of that div. and make it wrap around the device width or make it scroll horizontally.

**Expected Behavior**

make it wrap around the device width or make it scroll horizontally.

**Actual Behavior**

What happens instead?
This is happening because of overflow of div in which tags of photo like (Nature, Shoes, Camera, Birds, ...) have written

**Screenshots (if applicable)**

Add screenshots or other media to help explain the issue.
![image](https://github.com/Vijaykv5/SnapGrid/assets/97459528/141f5850-6d8e-43d0-8a95-d65ee87cbb2a)

**expected screenshot**

https://github.com/Vijaykv5/SnapGrid/assets/97459528/6b9ddbc0-c579-4404-be5c-b76a43dee6b3

**Additional Information**

Add any other context or information about the issue here.

**Comment by aniketkuma-r** [comment]
Hey @Vijaykv5 I have showed the expected behaviour of the Page. Please Assign me this issue so that i can make a PR. as i have fixed the bug,

**Comment by aniketkuma-r** [comment]
Please assign me the issue Under Hacktoberfest2023 :)
Thank You

**Comment by JavidSumra** [comment]
Hey @aniketkuma-r i think you haven't noticed but i already raised the same issue #196  🤝

**Comment by Vijaykv5** [comment]
Solved #196
