### ISSUE TITLE
[FEATURE] Search page theme match with user's system theme

### ISSUE THREAD

**Issue by SumanKisku** [Vijaykv5/SnapGrid#209]
**Description**

Search page theme should be matched with User's system theme.

Visiting the search page and landing on light mode page isn't a good UX for dark theme users(like me)

**Comment by SumanKisku** [comment]
@Vijaykv5 hi what do you think about this feature?

**Comment by Vijaykv5** [comment]
They can toggle according to their needs @SumanKisku .. so Ig its not needed
