### ISSUE TITLE
[BUG] ui bug in the search page (contents has overflowed and broke the ui page)

### ISSUE THREAD

**Issue by muhammedsirajudeen** [Vijaykv5/SnapGrid#212]
**Description**
The ui page on search is broken on mobile devices
Please describe the Bug in detail.
The ui page on search page is broken on mobile devices proper overflowed are not set and due to that content is being overflowed and breaking the page
**Expected Behavior**
the page should be fully responsive on mobile devices
What should happen?

**Actual Behavior**

What happens instead?
the page gets broken in mobile devices
**Screenshots (if applicable)**
broken ui page
![image](https://github.com/Vijaykv5/SnapGrid/assets/43089951/4f42f0fe-6eeb-491c-8926-5fe7c83b811e)

Add screenshots or other media to help explain the issue.

**Additional Information**

Add any other context or information about the issue here.
can you add the hacktoberfest label and assign me this issue

**Comment by JavidSumra** [comment]
Hi @muhammedsirajudeen, I believe I have resolved this issue. Could you please verify it once?

**Comment by muhammedsirajudeen** [comment]
@JavidSumra Yep its resolved 👍
