### ISSUE TITLE
[FEATURE] Converting SnapGrid into PWA

### ISSUE THREAD

**Issue by JavidSumra** [Vijaykv5/SnapGrid#215]
**Description**
Converting our Snapgrid Web App into [PWA(Progressive Web App)](https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps).it offers cross-platform compatibility, offline capabilities, faster loading, app-like experiences, no app store dependency, automatic updates, low storage requirements, improved SEO, security, reduced development costs, improved user engagement, no installation hassles, analytics, and major browser support.

**Demo Video**

https://github.com/Vijaykv5/SnapGrid/assets/112365664/0d7893b6-b042-4960-8141-3701390cc794

Hello Vijaykv5, could you kindly respond to this feature request and ensure it is allocated to my task queue?

**Comment by JavidSumra** [comment]
Hey @Vijaykv5 Please Reply on this Issue.

**Comment by Vijaykv5** [comment]
No @JavidSumra Its a web product we don't need a PWA
