### ISSUE TITLE
DARK MODE COMPONENT, Header, Footer and some UI changes.

### ISSUE THREAD

**Issue by Roar022** [Vijaykv5/SnapGrid#22]
**Description**

I want to add dark mode component that will enable dark mode in website, want to add header section in which logo, dark mode button, Login, SignUp and pages can be redirects from header. Footer can contain contributers name, pages, discord, github link and many more.

Please assign this issue to me

**Comment by Vijaykv5** [comment]
Right now just do it for current component
We shall think about the footer sections and all later
@Roar022

**Comment by Roar022** [comment]
You mean only dark mode button or a header containing logo and dark mode button!!

**Comment by Vijaykv5** [comment]
No when toggled to dark mode, Everything should be dark mode as per current website

**Comment by Vijaykv5** [comment]
Instead of "login" button can we add an dark mode and light mode button
May be like this?
![images](https://github.com/Vijaykv5/Image-Searcher/assets/94985341/e3d306a1-cc4a-4758-afb0-f184a9b5db18)

**Comment by Vijaykv5** [comment]
> ![Screenshot_20230927_133129](https://user-images.githubusercontent.com/111555339/270906672-b6cb9a1f-f82b-4b7a-bf8d-dbbee682d150.png) Ok then I will add a header section which include logo and working dark mode button like this.

I can also the the github icon missing here... Please fix that too...

**Comment by Vijaykv5** [comment]
@Roar022 Are you working on this?

**Comment by Roar022** [comment]
yes, I will try to do it by today.

**Comment by Vijaykv5** [comment]
Cool 👌

> yes, I will try to do it by today.
