### ISSUE TITLE
[FEATURE] Feature of liking the photos and displaying them on other page.

### ISSUE THREAD

**Issue by Kunal7069** [Vijaykv5/SnapGrid#26]
A like button will be displayed on each photo and user can like it.
All these liked photos will be displayed on another page separately.

**Comment by Vijaykv5** [comment]
Yeah was about to add on it

**Comment by Kunal7069** [comment]
So sir please assign it to me

**Comment by Kunal7069** [comment]
I struck in a error

**Comment by Kunal7069** [comment]
@Vijaykv5 I saved the URLs of all the photos you are liking in a Excel file but then I come to know that we cannot read the Excel file in react js.
Now I am not able to display those photos on another page.l

**Comment by Vijaykv5** [comment]
Yeah @Kunal7069 ..We can't retrieve data from Excel file and all. also its a bad idea ..I think you can store the liked images into redux store. 
It would be more useful and standard

**Comment by Kunal7069** [comment]
Ok I will be working on it

**Comment by Kunal7069** [comment]
Sir did you register this project in hacktoberfest 2023?

**Comment by Kunal7069** [comment]
@Vijaykv5 sir when will hacktoberfest label will be added to this feature?
So that this will be included as a contribution for hacktoberfest..

**Comment by Vijaykv5** [comment]
> Sir did you register this project in hacktoberfest 2023?

Yes you can add a pr when ever you've done the work

**Comment by Kunal7069** [comment]
Ok sir

**Comment by Kunal7069** [comment]
@Vijaykv5 I raised the PR 
please review it

**Comment by Vijaykv5** [comment]
Please Resove the conflicts after that I'll merge @Kunal7069

**Comment by Kunal7069** [comment]
@Vijaykv5 Sir it first time I got the conflicts while raising the PR so that's why it is taking some time but soon I will be doing it..

**Comment by Kunal7069** [comment]
@Vijaykv5 sir I resolved the conflicts and also added a video demo please  review it
