### ISSUE TITLE
[BUG] Critical UI Bug Unearthed at 320px Screen Size: Navigational Nightmare

### ISSUE THREAD

**Issue by aniimessh** [Vijaykv5/SnapGrid#31]
**Description**

The UI bug discovered at a screen size of 320px involves a critical issue in the layout and functionality of our application. When the screen size is set to this specific dimension, the following problems occur.

**Expected Behavior**

At a screen size of 320px, we expect the application's user interface to be fully responsive and functional. All elements, including buttons, text fields, and navigation menus, should adapt and display correctly without any distortion or overlapping.

**Actual Behavior**

Instead, when the screen size is reduced to 320px:

Overlapping Elements: Elements within the interface overlap with each other, making it challenging for users to interact with the application. This includes buttons, which may become inaccessible or obscured.

Text Clipping: Text within buttons or labels may get clipped or truncated, rendering it unreadable or confusing to users.

Navigation Issues: The navigation menu may not collapse properly or may not display all menu items, leading to a compromised user experience.

Responsiveness Failures: Some UI elements may not resize appropriately, causing the overall layout to appear broken and disorganized

**Screenshots (if applicable)**

![image](https://github.com/Vijaykv5/Image-Searcher/assets/97246133/7865a806-cd02-4bbe-a51b-bd1ed04fdd49)

**Additional Information**

This issue is critical as it affects the usability and accessibility of our application on smaller screens, such as mobile devices. It needs immediate attention and resolution to ensure a seamless user experience across all screen sizes. Can i work on this UI bug ?

**Comment by Vijaykv5** [comment]
@aniimessh Are u working on it?

**Comment by aniimessh** [comment]
> @aniimessh Are u working on it?

yes i am

**Comment by aniimessh** [comment]
@Vijaykv5  check it now

**Comment by Vijaykv5** [comment]
@aniimessh Some merge conflicts. please fix it

**Comment by aniimessh** [comment]
@Vijaykv5  i have resolved many times
