### ISSUE TITLE
[FEATURE] Drag and Drop image and Search

### ISSUE THREAD

**Issue by Vijaykv5** [Vijaykv5/SnapGrid#37]
**Description**
To add a feature in which user can upload images an search 

**Expected Behavior**

The user can either navigate to search by Keywords/ Drag and drop images

**Actual Behavior**

Search should be based on the images added by the user

**Screenshots (if applicable)**

Add screenshots or other media to help explain the issue.

![Frame 1](https://github.com/Vijaykv5/Image-Searcher/assets/94985341/7ffb1c2b-359c-4ccb-bbc0-52a9b8fcc327)

Add any other context or information about the issue here.

You're free to develop accordingly. But when User clicks on drag and drop button, it should have corresponding field to drag and drop images and all other section should remains as same

**Comment by Labhk** [comment]
can u assign me this issue??

**Comment by dfordp** [comment]
Have you considered using a service like cloudinary which proides an image platform and allows images from pretty much every sources

**Comment by Vijaykv5** [comment]
Nope I haven't 

> Have you considered using a service like cloudinary which proides an image platform and allows images from pretty much every sources

**Comment by Vijaykv5** [comment]
@Labhk May you can tell me how you're gonna move towards it in terms of Tech

**Comment by Labhk** [comment]
> @Labhk May you can tell me how you're gonna move towards it in terms of Tech

From description of the feature, I get u want  to have option to upload a photo and then search for more photos that are related to uploaded
technical steps I can think of
1) build a drag & drop input to upload photo
2) use some API to detect and obtain what type, category or keywords that are related to uploaded img
3) pass the obtained data to unsplash api in query=""

for 2) I've found that we can use api like Google Cloud Vision API to get image labels
I'm not sure about this,do tell me if u have any good suggestion for this

**Comment by Vijaykv5** [comment]
Yeah Exactly but I tries google Lens Api ..but haven't worked well as I expected. 

Not Sure which API could we go with 

> > @Labhk May you can tell me how you're gonna move towards it in terms of Tech
> 
> From description of the feature, I get u want to have option to upload a photo and then search for more photos that are related to uploaded technical steps I can think of
> 
> 1. build a drag & drop input to upload photo
> 2. use some API to detect and obtain what type, category or keywords that are related to uploaded img
> 3. pass the obtained data to unsplash api in query=""
> 
> for 2) I've found that we can use api like Google Cloud Vision API to get image labels I'm not sure about this,do tell me if u have any good suggestion for this

**Comment by Labhk** [comment]
u can assign me this issue?

**Comment by Vijaykv5** [comment]
Ok @Labhk

**Comment by Labhk** [comment]
@Vijaykv5 
For API I used Clarifai, it have 40-60% accuracy 
https://docs.clarifai.com/api-guide/predict/images/

here's demo 


https://github.com/Vijaykv5/Image-Searcher/assets/79000376/f7db05db-4932-4439-a06a-1c79faa49375

And large size photo takes more time uploading 
Review this if u want some change in UI or anything
I'll make a PR later of this

**Comment by Vijaykv5** [comment]
cool but could you add make the styling of card as current one

**Comment by Vijaykv5** [comment]
Also one more thing i would like to add on, when user clicks on drag and drop the keywords button should be hidden/disabled

**Comment by Vijaykv5** [comment]
can we directly drag and drop when user clickes on it , it should takes to while file to select like that rather than manual dropping of images

**Comment by Labhk** [comment]
> cool but could you add make the styling of card as current one

which one, I didn't get it

**Comment by Labhk** [comment]
> Also one more thing i would like to add on, when user clicks on drag and drop the keywords button should be hidden/disabled

I can do that ,
but u don't want to toogle back to keywords??

**Comment by Labhk** [comment]
> can we directly drag and drop when user clickes on it , it should takes to while file to select like that rather than manual dropping of images

yeah I also thought that
![image](https://github.com/Vijaykv5/Image-Searcher/assets/79000376/75e97600-b3b3-4a63-884f-c45975256728)


How about this I add a select file button

**Comment by Vijaykv5** [comment]
> > can we directly drag and drop when user clickes on it , it should takes to while file to select like that rather than manual dropping of images
> 
> yeah I also thought that ![image](https://user-images.githubusercontent.com/79000376/271834906-75e97600-b3b3-4a63-884f-c45975256728.png)
> 
> How about this I add a select file button

Yes when toggled to Keywords, the Buttons should show on and while on Drag & Drop , it must be hidden

**Comment by Vijaykv5** [comment]
<img width="1435" alt="Screenshot 2023-10-01 at 8 23 04 PM" src="https://github.com/Vijaykv5/Image-Searcher/assets/94985341/a4325884-8468-4398-8583-3fe20b330d50">


The margin and padding of cards , its not looking good in your video attached

> > cool but could you add make the styling of card as current one
> 
> which one, I didn't get it

**Comment by Labhk** [comment]
![image](https://github.com/Vijaykv5/Image-Searcher/assets/79000376/bc9bffbe-b7ee-4701-a064-f1e808fb79b6)


Done, I'll make a PR now
