### ISSUE TITLE
[Enhancement] UI/UX improvements required 

### ISSUE THREAD

**Issue by ayushichoudhary-19** [Vijaykv5/SnapGrid#41]
**Description**

Here are a few suggestions I have:
1. Having a 'search' icon in the input field will enhance the UI.
2. The 'scroll-to-top' button's icon does not look good. It's a '^' typed from the keyboard, instead, I recommend using a Chevron Up Icon.
3. Right now, the landing page has a lot of empty space, adding a footer can resolve this.

I would like to work on this issue if the proposed suggestions align with the project's goals.

**Comment by Vijaykv5** [comment]
Looks cool @ayushichoudhary-19 

but for 3rd one I'm not sure what we can have in footer as its an SPA , we can't include links to other pages

**Comment by ayushichoudhary-19** [comment]
How about we add a "credit" section to the footer, with the text "Maintained by xyz"? If you think that's unnecessary, I can happily proceed with working on the other two suggestions.

Please let me know what you think, and assign the issue to me if you'd like me to proceed.

**Comment by Vijaykv5** [comment]
Yeah 3rd one I found unnecessary rn, may be we can look into that later in future.

You can proceed with 1 and 2

**Comment by ayushichoudhary-19** [comment]
![image](https://github.com/Vijaykv5/Image-Searcher/assets/73214455/bdfafc25-3b16-48a8-b2ab-5987fcac28b8)

I am getting this error, but don't actually know how to resolve it.

**Comment by Roar022** [comment]
yes this is the error also showing to me. Just type `{images && images.map(.... ` rest code remains same, to fix the Error. I think maintainer have to make a discord community as soon as possible so that we can discuss these error there.

**Comment by ayushichoudhary-19** [comment]
> {images && images.map(....

Thanks, it worked!

**Comment by ayushichoudhary-19** [comment]
Please review the PR: https://github.com/Vijaykv5/Image-Searcher/pull/58 for this issue.
