### ISSUE TITLE
[FEATURE] ADD Shimmer Effect

### ISSUE THREAD

**Issue by Vijaykv5** [Vijaykv5/SnapGrid#43]
**Description**

When Image renders on page, there should be an Shimmer UI 

**Expected Behavior**
Show Shimmer UI - enhances user experiance

**Screenshots (if applicable)**

![download (1)](https://github.com/Vijaykv5/Image-Searcher/assets/94985341/28975d08-b3ea-43ca-8dc6-a61c8817bccc)

This shimmer for each cards

**Additional Information**

 Feel free to add your ideas into it

**Comment by veerprakash28** [comment]
Hi, I can add this loading effect, assign this to me

**Comment by jainendra001** [comment]
Hi @Vijaykv5   I am really interested to work on this issue, I am currently a fullstack developer pursuing undergrad at IIT's , Could you please assign me this issue.

**Comment by Vijaykv5** [comment]
Its already done @jainendra001 
Please feel to check or raise valid issue 
Happy contributing 🚀
