### ISSUE TITLE
[BUG] Add a "No Images Found" Component if no search results are found

### ISSUE THREAD

**Issue by veerprakash28** [Vijaykv5/SnapGrid#56]
**Description**

If there are no images for the search then there is nothing on the screen 

**Expected Behavior**

There should be a No Images Found Component, if there are no images found

**Actual Behavior**

Blank screen with no images

**Screenshots (if applicable)**

<img width="1437" alt="Screenshot 2023-10-01 at 1 17 44 PM" src="https://github.com/Vijaykv5/Image-Searcher/assets/94482800/35f154b4-b99f-4d53-9ea5-1ad5a88ba892">

Please assign this issue to me, so that I can fix it

**Comment by 289Volts** [comment]
Please assign this issue to me so i can fix it

**Comment by Vijaykv5** [comment]
Go for it! @veerprakash28

**Comment by Vijaykv5** [comment]
> Please assign this issue to me so i can fix it

We are following first come, since already @veerprakash28 asked for it, I'm assigning him. Please feel free to check other issues :)

**Comment by jainendra001** [comment]
Hi @Vijaykv5 I am really interested to work on this issue, I am currently a fullstack developer pursuing undergrad at IIT's , Could you please assign me this issue.

**Comment by veerprakash28** [comment]
> Hi @Vijaykv5 I am really interested to work on this issue, I am currently a fullstack developer pursuing undergrad at IIT's , Could you please assign me this issue.

I have completed this issue on local, will raise a PR for this soon. You can check for other issues on the repository. Thanks
