### ISSUE TITLE
INFINITE SCROLL

### ISSUE THREAD

**Issue by Roar022** [Vijaykv5/SnapGrid#59]
**Description**

Implement an infinite scroll feature that enables users to continuously load and browse more image results without the need for manual pagination. This feature enhances the user experience by providing seamless access to a large number of images.

**Expected Behavior**

When user reaches end of screen automatically more images will load.

**Actual Behavior**

User have to click on next and previous button to navigate pages.

Please assign this issue to me. I want to work on this issue.

**Comment by Vijaykv5** [comment]
Cool go for it 👍
