### ISSUE TITLE
[BUG] Text Overlapping Images in Manual Search

### ISSUE THREAD

**Issue by premsaivarmachekuri** [Vijaykv5/SnapGrid#67]
**Description**

In our project, there is an issue related to the placement of text when searching for an image using a word. The problem occurs when users manually enter a search term, and the text appears in an undesirable location. However, when users select options provided, the text and image are correctly placed.

**Expected Behavior**

The expected behavior is that when users manually search for an image using a word, the text should not appear between the images. It should be displayed in a user-friendly manner, enhancing the overall experience.

**Actual Behavior**

Currently, when a word is manually entered for image search, the text is placed in a position that disrupts the user experience. This is not the intended behavior.

**Screenshots**'
*Mobile*: 
![image](https://github.com/Vijaykv5/Image-Searcher/assets/110842297/a1da5368-e5b1-4d3a-be12-08f37d242a77)
*Desktop*
![Issue Screenshot](https://github.com/Vijaykv5/Image-Searcher/assets/110842297/fbdd8bdb-b22e-4e8a-8fb9-7a3a6539175b)

**Additional Information**

This issue needs to be resolved as the misplaced text during manual searches creates a less-than-optimal user experience. The goal is to ensure that text placement is consistent and does not interfere with the images, regardless of whether users manually enter a search term or use predefined options.

**Comment by Vijaykv5** [comment]
Get started @premsaivarmachekuri

**Comment by pratyushsingha** [comment]
i am a biginner...i want to contribute in open source...
