### ISSUE TITLE
Change Name : SnapGrid

### ISSUE THREAD

**Issue by Vijaykv5** [Vijaykv5/SnapGrid#68]
I though of changing the name of the Project from **"Image-Searcher"** to **"SnapGrid"**

**Comment by Babunshil** [comment]
I want to work on this issue under hacktoberfest 2023. Please assign me .

**Comment by ayushichoudhary-19** [comment]
> I though of changing the name of the Project from **"Image-Searcher"** to **"SnapGrid"**

Sounds great! "SnapGrid" is a more distinctive and appealing name and can enhance the project's identity and recognition.

After this change is finalized, I would like to work on changing the name in the entire documentation and the Landing page, so please assign it to me.

**Comment by Vijaykv5** [comment]
> I want to work on this issue under hacktoberfest 2023. Please assign me .

Please change every thing with "**Image-Searcher**" to **SnapGrid** in documentation, contributing, website and evry where

**Comment by Vijaykv5** [comment]
> > I though of changing the name of the Project from **"Image-Searcher"** to **"SnapGrid"**
> 
> Sounds great! "SnapGrid" is a more distinctive and appealing name and can enhance the project's identity and recognition.
> 
> After this change is finalized, I would like to work on changing the name in the entire documentation and the Landing page, so please assign it to me.

Since @Babunshil asked first, I'm assigning him the issue. If he won't be able to do it, I shall assign you
