### ISSUE TITLE
[BUG] Reduce Size of Banner image

### ISSUE THREAD

**Issue by Vijaykv5** [Vijaykv5/SnapGrid#77]
**Description**

The Size of Banner image is High

**Expected Behavior**

Reduce the **Height** and **increase** the font-size of description a little bit 

**Actual Behavior**

**Screenshots (if applicable)**
<img width="1440" alt="Screenshot 2023-10-02 at 3 31 03 PM" src="https://github.com/Vijaykv5/SnapGrid/assets/94985341/fa3f4b90-4660-4f8a-a26b-5648b8f16e31">

Add screenshots or other media to help explain the issue.

**Additional Information**
The image must not be distorted

**Comment by Babunshil** [comment]
I want to work on this issue under Hacktoberfest2023

**Comment by Vijaykv5** [comment]
This issue will be assigned only when #63 has been closed

**Comment by Babunshil** [comment]
okey sir I am waiting

**Comment by jainendra001** [comment]
Hi @Vijaykv5 I am really interested to work on this issue, I am currently a fullstack developer pursuing undergrad at IIT's , Could you please assign me this issue.
