### ISSUE TITLE
[DOCS] Add Unsplash link and guide to get API key to the README file

### ISSUE THREAD

**Issue by EternoSeeker** [Vijaykv5/SnapGrid#80]
Description

The developers who will try the app themselves would need a Unsplash API key, so in the README.md file a link to unsplash website and also a link to " How to get unsplash API key " would  be really helpful for anyone who tried the app. Also it helps for easy navigation

Expected Behavior

Small section where we link the Unsplash website and tutorial article to make it feasible for users to access it.

Actual Behavior

It would be nice to save time of people and help them with the API keys

Screenshots (if applicable)

N/A

Additional Information

N/A

**Comment by EternoSeeker** [comment]
You can consider assigning this issue to me under hacktoberfest

**Comment by Vijaykv5** [comment]
Go for it 👍
