### ISSUE TITLE
[BUG] Need to fix spacing issue with the name, search bar and categories & fix responsive issue

### ISSUE THREAD

**Issue by alidotdeveloper** [Vijaykv5/SnapGrid#83]
**Description**

Here is issues I noticed:
1)  Spacing issue with name "Snap Grid" and search bar.
2)  Spacing issue with the category links and image shown under category
3)  Responsiveness issue in the section under categories links

**Expected Behavior**

1) Spacing should be same between them for 1&2
3) Section should properly responsive in mobile device

**Actual Behavior**

How it will fixed:
1)  Remove spacing using CSS and make sure it also fixed on mobile and tablet.
2)  Add some margin under the category so it should not look to much close.
3)  Add media queries and also the remove extra padding and margin in mobile view.

**Screenshots (if applicable)**

![Screenshot 2023-10-02 215903](https://github.com/Vijaykv5/SnapGrid/assets/74443787/89ddb08a-1e93-4a27-935f-84a649fbf617)

![WhatsApp Image 2023-10-02 at 21 54 38_fea04a5a](https://github.com/Vijaykv5/SnapGrid/assets/74443787/474e10a7-28c5-486e-9c2b-54a898de667a)

![WhatsApp Image 2023-10-02 at 21 54 52_686be786](https://github.com/Vijaykv5/SnapGrid/assets/74443787/6cc8458b-2ea5-4f49-8ce7-1a0fdfe0cfc1)

**Additional Information**

Add any other context or information about the issue here.

**Comment by Vijaykv5** [comment]
Could you make it over all responsive on all devices and fix that spacing issues too @alidotdeveloper

**Comment by Vijaykv5** [comment]
its taken care in #90 
I'm closing this issue now. Please feel to discover other issues :)
