### ISSUE TITLE
site is being crashed while running on localhost

### ISSUE THREAD

**Issue by Jaskamalsingh** [Vijaykv5/SnapGrid#84]
As directed in the readme file i cloned your project , added my own api key in .env file but then also the site is not showing images . Please guide how to solve this issue

https://github.com/Vijaykv5/SnapGrid/assets/97536525/56df33dd-b57c-4283-916e-20ec5708eaf7

**Comment by Vijaykv5** [comment]
Please do a git pull and then do npm start @Jaskamalsingh

**Comment by Jaskamalsingh** [comment]
okay

**Comment by Jaskamalsingh** [comment]
I tried git pull and then did npm start but still it's not working

**Comment by Vijaykv5** [comment]
I now tried locally according to your request. its working fine for me. Check the console and look whether its throwing any errors.

The site your seeing id **Old** and it has been updated lately

**Comment by Vijaykv5** [comment]
@Jaskamalsingh does it worked now?

**Comment by Vijaykv5** [comment]
@Jaskamalsingh I'm closing this issue now. If you face any issue in setup ask queries in [discord](https://discord.gg/9NC8xVV9)
