### ISSUE TITLE
[BUG] Making Banner and description responsive

### ISSUE THREAD

**Issue by rutikgagare** [Vijaykv5/SnapGrid#90]
**Actual Behavior**
In Mobile View the description and banner is not responsive or not properly styled .

**Expected Behavior**
So we can bring banner down the description or upside of the description instead of keeping them in a row.

**Screenshots (if applicable)**
![snapGrid](https://github.com/Vijaykv5/SnapGrid/assets/85502114/d906ff03-0350-4322-9f4c-27b89ca836fb)

**Additional Information**

Can you please assign this issue to me @Vijaykv5

**Comment by Vijaykv5** [comment]
Could you make the whole website responsive @rutikgagare

**Comment by rutikgagare** [comment]
yes I will make whole website responsive

**Comment by Vijaykv5** [comment]
cool . go for it @rutikgagare

**Comment by Vijaykv5** [comment]
@rutikgagare are you working on it?

**Comment by TandinDev** [comment]
@Vijaykv5 I can work on it. If there are any opportunities.

**Comment by rutikgagare** [comment]
Sorry as It is completely in tailwind but I work mostly with normal CSS I thought It might not work for you. If you are okay with normal CSS I can do that else you can assign it to another.

**Comment by Vijaykv5** [comment]
Ok @rutikgagare I would like to maintain for tailwind itself
I'm closing this issue . You're free to look on other issues 
Thanks

**Comment by Vijaykv5** [comment]
@TandinDev Would you like to work on it??

**Comment by TandinDev** [comment]
Sure, I can this issue. Thank you for the opportunity.

**Comment by Vijaykv5** [comment]
Go for it @TandinDev
I'm making it as high priority

**Comment by TandinDev** [comment]
@Vijaykv5 I have resolve this issue in the following PR: https://github.com/Vijaykv5/SnapGrid/pull/128

**Comment by TandinDev** [comment]
Hello @Vijaykv5 can you please attach an label hactoberfest and hacktober accepted?

**Comment by Vijaykv5** [comment]
The repo is under hacktoberfest label , so no issues it will be counted

**Comment by TandinDev** [comment]
Hello @Vijaykv5 can you also please review this PR: https://github.com/Vijaykv5/SnapGrid/pull/129
