### ISSUE TITLE
[FEATURE] Changing the search box title

### ISSUE THREAD

**Issue by thecodereule** [Vijaykv5/SnapGrid#91]
**Description**
The text inside of the search box should be changed
![image](https://github.com/Vijaykv5/SnapGrid/assets/97162709/9812d3eb-1a15-43bd-a016-5b27e4730d42)

"Try Something Search here ..." doesn't sound appealing.

I propose that we change it to just "Search here".
It gives off a much more professional, clean look. And the website design itself should be enough for the user to know what they're supposed to do on the website.

Just look at examples of Google image search, and you will see that they have no text there at all.

![image](https://github.com/Vijaykv5/SnapGrid/assets/97162709/921afb43-e810-4ead-a171-0624059cf407)

**Comment by Vijaykv5** [comment]
I think it's fine to have a placeholder...

**Comment by thecodereule** [comment]
Yes but that sentance doesn't work grammatically. I propose simply "Search here..." would look better

**Comment by DavOlufuwa** [comment]
Yes "Search here..." would work better

**Comment by thecodereule** [comment]
I am working on it.

**Comment by Vijaykv5** [comment]
Cool
