### ISSUE TITLE
[BUG] In search bar

### ISSUE THREAD

**Issue by RahulGIT24** [Vijaykv5/SnapGrid#93]
**Description**

When I search for an image in search bar for eg. Games. Then it shows nothing and even if I enter travel It also shows nothing. That's the bug

**Expected Behavior**

If I search something which is not available then It should show not found and If I search something which exist it should show that particular Image with it's description.

What happens instead?

If you find it relevant please assign this to me and mark as hacktoberfest-accepted

**Comment by Vijaykv5** [comment]
<img width="1440" alt="Screenshot 2023-10-03 at 6 46 58 PM" src="https://github.com/Vijaykv5/SnapGrid/assets/94985341/03b0e2b7-9530-4a47-808a-8bc2fa97d247">
 @RahulGIT24 its actually working

**Comment by RahulGIT24** [comment]
I think it's api key issue

**Comment by ManuPrasad1208** [comment]
Assign me this issue. I have checked locally...it looks i can fix it!

**Comment by Vijaykv5** [comment]
What's the issue its working fine for all. May be you added wrong api key

**Comment by Vijaykv5** [comment]
What's the issue its working fine for all. May be you

**Comment by RahulGIT24** [comment]
Yes I thik I entered a wrong one. I think we should ask user on client side to enter api key if it's not available.
