### ISSUE TITLE
[BUG] Image Grid Fix

### ISSUE THREAD

**Issue by vaibhava17** [Vijaykv5/SnapGrid#94]
**Description**
Image Grid is not responsive or fuild sometime.

**Expected Behavior**
To be responsive and adjust to screen size

**Actual Behavior**
Not completely responsive and can overlap on one another in some screen size

**Screenshots (if applicable)**
<img width="1085" alt="image" src="https://github.com/Vijaykv5/SnapGrid/assets/65801959/6ff1863d-bf4e-418f-84d7-4501ec700ad5">

Please allow me to work not it under hacktoberfest

**Comment by Vijaykv5** [comment]
@vaibhava17 Its taken care in #90
